### ISSUE TITLE
Problema con widget_id en Document

### ISSUE THREAD

**Issue by gabrielchavezme** [Mifiel/php-api-client#8]
Revisando la documentación oficial (https://docs.mifiel.com/#document), en el object de Document hay un parámetro llamado widget_id, el cual no se está retornando en las peticiones del lado del servidor.

Esto genera un problema al renderizar Embedded Signing del lado del cliente, ya que no hay forma de pasarle el widget_id porque no existe.

Desde Embedded Signing intente enviar el ID del documento ya que es el único identificador que devuelve la API, sin embargo siempre me retorna un error 404 (aquí no hay documento), como si no encontrará el documento en mi cuenta.

```
<script type="text/javascript">
    window.mifiel.widget({
      widgetId: "{{ $acta->mifiel['id'] }}",
      appendTo: 'mifiel',
      successBtnText: 'Proceed to next step'
    });
  </script>
```

¿Hay alguna forma de obtener este valor?, quiero pensar que quizás es error de mi lado, pero revisando la documentación, en teoría debería retornar ese valor.

**Comment by ezavile** [comment]
Hola @gabrielchavezme, el `widget_id` es un valor que tiene cada firmante, para acceder a ese atributo, puedes obtenerlo a este nivel del response del documento: `document.signers[n].widget_id`.

En caso de que no tengas a la mano  la información completa del documento, vas a tener que hacer un `find` del documento algo como `$document = Document::find('id');`.
